# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 一只皮卡丘
subtitle: 'never lose the child-like wonder'
description: 'about js'
keywords: js
author: peacejj
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 3
  order_by: -date

  # Category & Tag
  default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD HH:mm:ss
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: fluid

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

banner_img: /images/bg.png

navbar:
  blog_title: 一只皮卡丘

# 关于页
about:
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/peacejj', tip: 'GitHub' }
  avatar: https://avatars.githubusercontent.com/u/27217020?v=4
  name: "peacejj"
  intro: "路上ing"
  banner_img: /images/banner/bg5.jpg   # 对应存放在 /source/img/bg/example.jpg


web_analytics:  # 网页访问统计
  enable: true # 默认为false，启用网页统计改为true即可
  leancloud:  # LeanCloud 计数统计，可用于 PV UV 展示，如果 web_analytics.enable 没有开启，PV UV 展示只会查询，不会增加
    app_id: z0tbdI48i6n76Caa0MN6garl-gzGzoHsz
    app_key: bWBLgXQjDRhEJfygVbFPm92b
    server_url: https://z0tbdi48.lc-cn-n1-shared.com # REST API 服务器地址，国际版不
footer:
  statistics:
    enable: true
    source: "leancloud"  # 可选 leancloud | busuanzi  根据自己需求选择
    pv_format: "总访问量 {} 次"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    uv_format: "总访客数 {} 人"

# 主题暗色模式
dark_mode:
  enable: true
  default: auto

# 首页
index:
  slogan:
    enable: true
    text:
  post_url_target: _blank
  banner_img: /images/banner/bg.jpg   # 对应存放在 /source/img/bg/example.jpg

archive:
  banner_img: /images/banner/bg1.jpg   # 对应存放在 /source/img/bg/example.jpg

category:
  banner_img: /images/banner/bg2.jpg   # 对应存放在 /source/img/bg/example.jpg

tag:
  banner_img: /images/banner/bg4.jpg   # 对应存放在 /source/img/bg/example.jpg
  banner_img_height: 60

# 文章统计
post:
  meta:
    views:  # 阅读次数
      enable: true
      source: "leancloud"  # 统计数据来源，可选：leancloud | busuanzi   注意不蒜子会间歇抽风
      format: "{} 次"
  comments:
    enable: true
    type: valine

valine:
  appid:
  appkey:
  placeholder: 留下你的足迹~ # 评论框占位提示符
  path: window.location.pathname # 当前文章页路径，用于区分不同的文章页，以保证正确读取该文章页下的评论列表
  avatar: retro # Gravatar 头像展示方式
  meta: ['nick', 'mail', 'link']  # 评论者相关属性
  pageSize: 10 # 评论列表分页，每页条数
  lang: zh-CN # zh-CN | zh-TW | en | ja
  highlight: true # 代码高亮
  recordIP: true # 是否记录评论者IP
  serverURLs:  # REST API 服务器地址，国际版不填


# 代码设置
code:
  copy_btn: true
  highlight:
    enable: true
    line_number: true
    lib: "highlightjs"
    highlightjs:
      style: 'Github Gist'
      bg_color: false
    prismjs:
      style: "default"
      preprocess: true
